# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: graph.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "graph.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bgraph.proto\x12\x05graph"\x9d\x01\n\x16GetGraphContextRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\r\n\x05query\x18\x03 \x01(\t\x12\x11\n\tmax_nodes\x18\x04 \x01(\x05\x12\x11\n\tmax_depth\x18\x05 \x01(\x05\x12\x12\n\nmax_tokens\x18\x06 \x01(\x05\x12\x10\n\x08trace_id\x18\x07 \x01(\t"K\n\x14GetNodesByIdsRequest\x12\x10\n\x08node_ids\x18\x01 \x03(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08trace_id\x18\x03 \x01(\t"\xc0\x01\n\tGraphNode\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x11\n\tnode_type\x18\x03 \x01(\t\x12\x34\n\nproperties\x18\x04 \x03(\x0b\x32 .graph.GraphNode.PropertiesEntry\x12\x17\n\x0frelevance_score\x18\x05 \x01(\x02\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"\xc9\x01\n\x11GraphRelationship\x12\x14\n\x0c\x66rom_node_id\x18\x01 \x01(\t\x12\x12\n\nto_node_id\x18\x02 \x01(\t\x12\x19\n\x11relationship_type\x18\x03 \x01(\t\x12<\n\nproperties\x18\x04 \x03(\x0b\x32(.graph.GraphRelationship.PropertiesEntry\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"\xaf\x01\n\x17GetGraphContextResponse\x12\x1f\n\x05nodes\x18\x01 \x03(\x0b\x32\x10.graph.GraphNode\x12/\n\rrelationships\x18\x02 \x03(\x0b\x32\x18.graph.GraphRelationship\x12\x18\n\x10subgraph_summary\x18\x03 \x01(\t\x12\x14\n\x0ctotal_tokens\x18\x04 \x01(\x05\x12\x12\n\nrequest_id\x18\x05 \x01(\t"8\n\x15GetNodesByIdsResponse\x12\x1f\n\x05nodes\x18\x01 \x03(\x0b\x32\x10.graph.GraphNode2\xac\x01\n\x0cGraphService\x12P\n\x0fGetGraphContext\x12\x1d.graph.GetGraphContextRequest\x1a\x1e.graph.GetGraphContextResponse\x12J\n\rGetNodesByIds\x12\x1b.graph.GetNodesByIdsRequest\x1a\x1c.graph.GetNodesByIdsResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "graph_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GRAPHNODE_PROPERTIESENTRY"]._loaded_options = None
    _globals["_GRAPHNODE_PROPERTIESENTRY"]._serialized_options = b"8\001"
    _globals["_GRAPHRELATIONSHIP_PROPERTIESENTRY"]._loaded_options = None
    _globals["_GRAPHRELATIONSHIP_PROPERTIESENTRY"]._serialized_options = b"8\001"
    _globals["_GETGRAPHCONTEXTREQUEST"]._serialized_start = 23
    _globals["_GETGRAPHCONTEXTREQUEST"]._serialized_end = 180
    _globals["_GETNODESBYIDSREQUEST"]._serialized_start = 182
    _globals["_GETNODESBYIDSREQUEST"]._serialized_end = 257
    _globals["_GRAPHNODE"]._serialized_start = 260
    _globals["_GRAPHNODE"]._serialized_end = 452
    _globals["_GRAPHNODE_PROPERTIESENTRY"]._serialized_start = 403
    _globals["_GRAPHNODE_PROPERTIESENTRY"]._serialized_end = 452
    _globals["_GRAPHRELATIONSHIP"]._serialized_start = 455
    _globals["_GRAPHRELATIONSHIP"]._serialized_end = 656
    _globals["_GRAPHRELATIONSHIP_PROPERTIESENTRY"]._serialized_start = 403
    _globals["_GRAPHRELATIONSHIP_PROPERTIESENTRY"]._serialized_end = 452
    _globals["_GETGRAPHCONTEXTRESPONSE"]._serialized_start = 659
    _globals["_GETGRAPHCONTEXTRESPONSE"]._serialized_end = 834
    _globals["_GETNODESBYIDSRESPONSE"]._serialized_start = 836
    _globals["_GETNODESBYIDSRESPONSE"]._serialized_end = 892
    _globals["_GRAPHSERVICE"]._serialized_start = 895
    _globals["_GRAPHSERVICE"]._serialized_end = 1067
# @@protoc_insertion_point(module_scope)
