# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from app.grpc.proto import graph_pb2 as graph__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in graph_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class GraphServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGraphContext = channel.unary_unary(
            "/graph.GraphService/GetGraphContext",
            request_serializer=graph__pb2.GetGraphContextRequest.SerializeToString,
            response_deserializer=graph__pb2.GetGraphContextResponse.FromString,
            _registered_method=True,
        )
        self.GetNodesByIds = channel.unary_unary(
            "/graph.GraphService/GetNodesByIds",
            request_serializer=graph__pb2.GetNodesByIdsRequest.SerializeToString,
            response_deserializer=graph__pb2.GetNodesByIdsResponse.FromString,
            _registered_method=True,
        )


class GraphServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetGraphContext(self, request, context):
        """Fetch relevant graph context for a query"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetNodesByIds(self, request, context):
        """Fetch specific nodes by ID"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetGraphContext": grpc.unary_unary_rpc_method_handler(
            servicer.GetGraphContext,
            request_deserializer=graph__pb2.GetGraphContextRequest.FromString,
            response_serializer=graph__pb2.GetGraphContextResponse.SerializeToString,
        ),
        "GetNodesByIds": grpc.unary_unary_rpc_method_handler(
            servicer.GetNodesByIds,
            request_deserializer=graph__pb2.GetNodesByIdsRequest.FromString,
            response_serializer=graph__pb2.GetNodesByIdsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "graph.GraphService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("graph.GraphService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class GraphService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGraphContext(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/graph.GraphService/GetGraphContext",
            graph__pb2.GetGraphContextRequest.SerializeToString,
            graph__pb2.GetGraphContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetNodesByIds(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/graph.GraphService/GetNodesByIds",
            graph__pb2.GetNodesByIdsRequest.SerializeToString,
            graph__pb2.GetNodesByIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
