# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "llm_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11llm_service.proto\x12\x0bllm_service"\x14\n\x12HealthCheckRequest"6\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t"\x17\n\x15ProviderHealthRequest"\xa1\x01\n\x16ProviderHealthResponse\x12P\n\x0fprovider_status\x18\x01 \x03(\x0b\x32\x37.llm_service.ProviderHealthResponse.ProviderStatusEntry\x1a\x35\n\x13ProviderStatusEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"\x1c\n\x1aWorkflowEngineStatsRequest"\xd0\x01\n\x1bWorkflowEngineStatsResponse\x12\x16\n\x0etotal_requests\x18\x01 \x01(\x03\x12^\n\x14mode_dispatch_counts\x18\x02 \x03(\x0b\x32@.llm_service.WorkflowEngineStatsResponse.ModeDispatchCountsEntry\x1a\x39\n\x17ModeDispatchCountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01"`\n\x15\x44irectCompleteRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04mode\x18\x04 \x01(\t"8\n\x16\x44irectCompleteResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07is_last\x18\x02 \x01(\x08\x32\x86\x03\n\nLLMService\x12P\n\x0bHealthCheck\x12\x1f.llm_service.HealthCheckRequest\x1a .llm_service.HealthCheckResponse\x12\\\n\x11GetProviderHealth\x12".llm_service.ProviderHealthRequest\x1a#.llm_service.ProviderHealthResponse\x12k\n\x16GetWorkflowEngineStats\x12\'.llm_service.WorkflowEngineStatsRequest\x1a(.llm_service.WorkflowEngineStatsResponse\x12[\n\x0e\x44irectComplete\x12".llm_service.DirectCompleteRequest\x1a#.llm_service.DirectCompleteResponse0\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "llm_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PROVIDERHEALTHRESPONSE_PROVIDERSTATUSENTRY"]._loaded_options = None
    _globals["_PROVIDERHEALTHRESPONSE_PROVIDERSTATUSENTRY"]._serialized_options = b"8\001"
    _globals["_WORKFLOWENGINESTATSRESPONSE_MODEDISPATCHCOUNTSENTRY"]._loaded_options = None
    _globals["_WORKFLOWENGINESTATSRESPONSE_MODEDISPATCHCOUNTSENTRY"]._serialized_options = b"8\001"
    _globals["_HEALTHCHECKREQUEST"]._serialized_start = 34
    _globals["_HEALTHCHECKREQUEST"]._serialized_end = 54
    _globals["_HEALTHCHECKRESPONSE"]._serialized_start = 56
    _globals["_HEALTHCHECKRESPONSE"]._serialized_end = 110
    _globals["_PROVIDERHEALTHREQUEST"]._serialized_start = 112
    _globals["_PROVIDERHEALTHREQUEST"]._serialized_end = 135
    _globals["_PROVIDERHEALTHRESPONSE"]._serialized_start = 138
    _globals["_PROVIDERHEALTHRESPONSE"]._serialized_end = 299
    _globals["_PROVIDERHEALTHRESPONSE_PROVIDERSTATUSENTRY"]._serialized_start = 246
    _globals["_PROVIDERHEALTHRESPONSE_PROVIDERSTATUSENTRY"]._serialized_end = 299
    _globals["_WORKFLOWENGINESTATSREQUEST"]._serialized_start = 301
    _globals["_WORKFLOWENGINESTATSREQUEST"]._serialized_end = 329
    _globals["_WORKFLOWENGINESTATSRESPONSE"]._serialized_start = 332
    _globals["_WORKFLOWENGINESTATSRESPONSE"]._serialized_end = 540
    _globals["_WORKFLOWENGINESTATSRESPONSE_MODEDISPATCHCOUNTSENTRY"]._serialized_start = 483
    _globals["_WORKFLOWENGINESTATSRESPONSE_MODEDISPATCHCOUNTSENTRY"]._serialized_end = 540
    _globals["_DIRECTCOMPLETEREQUEST"]._serialized_start = 542
    _globals["_DIRECTCOMPLETEREQUEST"]._serialized_end = 638
    _globals["_DIRECTCOMPLETERESPONSE"]._serialized_start = 640
    _globals["_DIRECTCOMPLETERESPONSE"]._serialized_end = 696
    _globals["_LLMSERVICE"]._serialized_start = 699
    _globals["_LLMSERVICE"]._serialized_end = 1089
# @@protoc_insertion_point(module_scope)
