# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from app.grpc.proto import llm_service_pb2 as llm__service__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in llm_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class LLMServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
            "/llm_service.LLMService/HealthCheck",
            request_serializer=llm__service__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=llm__service__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )
        self.GetProviderHealth = channel.unary_unary(
            "/llm_service.LLMService/GetProviderHealth",
            request_serializer=llm__service__pb2.ProviderHealthRequest.SerializeToString,
            response_deserializer=llm__service__pb2.ProviderHealthResponse.FromString,
            _registered_method=True,
        )
        self.GetWorkflowEngineStats = channel.unary_unary(
            "/llm_service.LLMService/GetWorkflowEngineStats",
            request_serializer=llm__service__pb2.WorkflowEngineStatsRequest.SerializeToString,
            response_deserializer=llm__service__pb2.WorkflowEngineStatsResponse.FromString,
            _registered_method=True,
        )
        self.DirectComplete = channel.unary_stream(
            "/llm_service.LLMService/DirectComplete",
            request_serializer=llm__service__pb2.DirectCompleteRequest.SerializeToString,
            response_deserializer=llm__service__pb2.DirectCompleteResponse.FromString,
            _registered_method=True,
        )


class LLMServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetProviderHealth(self, request, context):
        """Get current provider health status (groq, nvidia, gemini)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetWorkflowEngineStats(self, request, context):
        """Get current Workflow Engine dispatch stats (mode_handler vs langgraph split)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DirectComplete(self, request, context):
        """Trigger a direct (non-Kafka) completion for internal tools (admin only)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=llm__service__pb2.HealthCheckRequest.FromString,
            response_serializer=llm__service__pb2.HealthCheckResponse.SerializeToString,
        ),
        "GetProviderHealth": grpc.unary_unary_rpc_method_handler(
            servicer.GetProviderHealth,
            request_deserializer=llm__service__pb2.ProviderHealthRequest.FromString,
            response_serializer=llm__service__pb2.ProviderHealthResponse.SerializeToString,
        ),
        "GetWorkflowEngineStats": grpc.unary_unary_rpc_method_handler(
            servicer.GetWorkflowEngineStats,
            request_deserializer=llm__service__pb2.WorkflowEngineStatsRequest.FromString,
            response_serializer=llm__service__pb2.WorkflowEngineStatsResponse.SerializeToString,
        ),
        "DirectComplete": grpc.unary_stream_rpc_method_handler(
            servicer.DirectComplete,
            request_deserializer=llm__service__pb2.DirectCompleteRequest.FromString,
            response_serializer=llm__service__pb2.DirectCompleteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "llm_service.LLMService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("llm_service.LLMService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class LLMService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/llm_service.LLMService/HealthCheck",
            llm__service__pb2.HealthCheckRequest.SerializeToString,
            llm__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetProviderHealth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/llm_service.LLMService/GetProviderHealth",
            llm__service__pb2.ProviderHealthRequest.SerializeToString,
            llm__service__pb2.ProviderHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetWorkflowEngineStats(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/llm_service.LLMService/GetWorkflowEngineStats",
            llm__service__pb2.WorkflowEngineStatsRequest.SerializeToString,
            llm__service__pb2.WorkflowEngineStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DirectComplete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/llm_service.LLMService/DirectComplete",
            llm__service__pb2.DirectCompleteRequest.SerializeToString,
            llm__service__pb2.DirectCompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
