# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from app.grpc.proto import memory_pb2 as memory__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in memory_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MemoryServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMemoryContext = channel.unary_unary(
            "/memory.MemoryService/GetMemoryContext",
            request_serializer=memory__pb2.GetMemoryContextRequest.SerializeToString,
            response_deserializer=memory__pb2.GetMemoryContextResponse.FromString,
            _registered_method=True,
        )
        self.GetShortTermMemory = channel.unary_unary(
            "/memory.MemoryService/GetShortTermMemory",
            request_serializer=memory__pb2.GetShortTermMemoryRequest.SerializeToString,
            response_deserializer=memory__pb2.GetShortTermMemoryResponse.FromString,
            _registered_method=True,
        )


class MemoryServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetMemoryContext(self, request, context):
        """Fetch all relevant memory context for a conversation"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetShortTermMemory(self, request, context):
        """Fetch only short-term conversation history"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetMemoryContext": grpc.unary_unary_rpc_method_handler(
            servicer.GetMemoryContext,
            request_deserializer=memory__pb2.GetMemoryContextRequest.FromString,
            response_serializer=memory__pb2.GetMemoryContextResponse.SerializeToString,
        ),
        "GetShortTermMemory": grpc.unary_unary_rpc_method_handler(
            servicer.GetShortTermMemory,
            request_deserializer=memory__pb2.GetShortTermMemoryRequest.FromString,
            response_serializer=memory__pb2.GetShortTermMemoryResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "memory.MemoryService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("memory.MemoryService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class MemoryService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMemoryContext(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/memory.MemoryService/GetMemoryContext",
            memory__pb2.GetMemoryContextRequest.SerializeToString,
            memory__pb2.GetMemoryContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetShortTermMemory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/memory.MemoryService/GetShortTermMemory",
            memory__pb2.GetShortTermMemoryRequest.SerializeToString,
            memory__pb2.GetShortTermMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
