# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retrieval.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "retrieval.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fretrieval.proto\x12\tretrieval"\xe1\x01\n\x18GetRelevantChunksRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\r\n\x05query\x18\x03 \x01(\t\x12\r\n\x05top_k\x18\x04 \x01(\x05\x12(\n\x05scope\x18\x05 \x01(\x0e\x32\x19.retrieval.RetrievalScope\x12\x10\n\x08\x66ile_ids\x18\x06 \x03(\t\x12\x1b\n\x13min_relevance_score\x18\x07 \x01(\x02\x12\x12\n\nmax_tokens\x18\x08 \x01(\x05\x12\x10\n\x08trace_id\x18\t \x01(\t"\xe3\x01\n\rDocumentChunk\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x16\n\x0esource_file_id\x18\x03 \x01(\t\x12\x13\n\x0bsource_name\x18\x04 \x01(\t\x12\x17\n\x0frelevance_score\x18\x05 \x01(\x02\x12\x38\n\x08metadata\x18\x06 \x03(\x0b\x32&.retrieval.DocumentChunk.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"o\n\x19GetRelevantChunksResponse\x12(\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\x18.retrieval.DocumentChunk\x12\x14\n\x0ctotal_tokens\x18\x02 \x01(\x05\x12\x12\n\nrequest_id\x18\x03 \x01(\t*8\n\x0eRetrievalScope\x12\t\n\x05\x46ILES\x10\x00\x12\x12\n\x0eKNOWLEDGE_BASE\x10\x01\x12\x07\n\x03\x41LL\x10\x02\x32r\n\x10RetrievalService\x12^\n\x11GetRelevantChunks\x12#.retrieval.GetRelevantChunksRequest\x1a$.retrieval.GetRelevantChunksResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "retrieval_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DOCUMENTCHUNK_METADATAENTRY"]._loaded_options = None
    _globals["_DOCUMENTCHUNK_METADATAENTRY"]._serialized_options = b"8\001"
    _globals["_RETRIEVALSCOPE"]._serialized_start = 601
    _globals["_RETRIEVALSCOPE"]._serialized_end = 657
    _globals["_GETRELEVANTCHUNKSREQUEST"]._serialized_start = 31
    _globals["_GETRELEVANTCHUNKSREQUEST"]._serialized_end = 256
    _globals["_DOCUMENTCHUNK"]._serialized_start = 259
    _globals["_DOCUMENTCHUNK"]._serialized_end = 486
    _globals["_DOCUMENTCHUNK_METADATAENTRY"]._serialized_start = 439
    _globals["_DOCUMENTCHUNK_METADATAENTRY"]._serialized_end = 486
    _globals["_GETRELEVANTCHUNKSRESPONSE"]._serialized_start = 488
    _globals["_GETRELEVANTCHUNKSRESPONSE"]._serialized_end = 599
    _globals["_RETRIEVALSERVICE"]._serialized_start = 659
    _globals["_RETRIEVALSERVICE"]._serialized_end = 773
# @@protoc_insertion_point(module_scope)
