# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from app.grpc.proto import retrieval_pb2 as retrieval__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in retrieval_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RetrievalServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRelevantChunks = channel.unary_unary(
            "/retrieval.RetrievalService/GetRelevantChunks",
            request_serializer=retrieval__pb2.GetRelevantChunksRequest.SerializeToString,
            response_deserializer=retrieval__pb2.GetRelevantChunksResponse.FromString,
            _registered_method=True,
        )


class RetrievalServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetRelevantChunks(self, request, context):
        """Retrieve top-k relevant document chunks"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RetrievalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetRelevantChunks": grpc.unary_unary_rpc_method_handler(
            servicer.GetRelevantChunks,
            request_deserializer=retrieval__pb2.GetRelevantChunksRequest.FromString,
            response_serializer=retrieval__pb2.GetRelevantChunksResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "retrieval.RetrievalService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("retrieval.RetrievalService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RetrievalService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRelevantChunks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/retrieval.RetrievalService/GetRelevantChunks",
            retrieval__pb2.GetRelevantChunksRequest.SerializeToString,
            retrieval__pb2.GetRelevantChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
